apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  UI_SECRET: "65jVEj0cI2JCUbVQ"
  JOBSERVICE_SECRET: "M2H76n8IZU1SE4Lm"
  SECRET_KEY: "uYnIdWjd4IFLotVi"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  GODEBUG: netdns=cgo
  CONFIG_PATH: /etc/jobservice/app.conf
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
